<?php

namespace Feature\Api\Post;

use App\Models\Post;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class UpdatePostTest extends TestCase
{
    use RefreshDatabase;

    private Post $post;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();

        $this->post = Post::factory()
            ->for($this->user, 'author')
            ->create();
    }

    /**
     * A basic feature test example.
     */
    public function test_update_post(): void
    {
        // sail artisan test --filter=UpdatePostTest
        $post = Post::factory()->make();
        //dump($post);
        //dump($this->post);

        // вот эта штука покажет дополнительные ошибки!
        $this->withoutExceptionHandling();

//        $response = $this->actingAs($this->user)
//            ->post(route('post.update', $this->post), $post->getAttributes())
//            //->assertSessionHasNoErrors() // эта штука также выдает ошибку!
//        ;

        // это выдает 422 ошибку, но непонятно где именно ошибка
        $response = $this
            ->actingAs($this->user)
            ->json('put', route('post.update', $this->post), $post->getAttributes());

        //$response->dump();
        $response->assertOk();
    }
}
