<?php

namespace Feature\Api\Company;

use App\Models\Company;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class StoreCompanyTest extends TestCase
{
    use RefreshDatabase;
    private User $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = User::factory()->create();
    }

    /**
     * A basic feature test example.
     */
    public function test_store_company(): void
    {
        // sail artisan test --filter=StoreCompanyTest

        $company = Company::factory()->make();
        $company->spokesperson_id = $this->user->id;

        // вот эта штука покажет дополнительные ошибки!
        $this->withoutExceptionHandling();

        $response = $this->actingAs($this->user)
            ->post(route('company.store'), $company->getAttributes())
            //->assertSessionHasNoErrors() // эта штука также выдает ошибку!
        ;

        // это выдает 422 ошибку, но непонятно где именно ошибка
        //$response = $this->actingAs($this->user)
        //    ->json('POST', route('post.store'), $this->post->getAttributes());

        $response->assertCreated();

        $response->assertJsonIsObject();

        $response->assertJson([
            'name' => $company->name,
        ]);

        $this->assertDatabaseHas(
            'companies',
            $company->toArray()
        );
    }
}
